# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!
use_modular_headers!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'HouseholdBudget' do
  config = use_native_modules!

  pod 'RNWorklets', :path => '../node_modules/react-native-worklets'
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    # Fix 1: Create gRPC-Core modulemap symlink
    grpc_dir = File.join(installer.sandbox.root, "Headers", "Private", "grpc")
    FileUtils.mkdir_p(grpc_dir)
    src = File.join(installer.sandbox.root, "Target Support Files", "gRPC-Core", "gRPC-Core.modulemap")
    dst = File.join(grpc_dir, "gRPC-Core.modulemap")
    FileUtils.ln_sf(src, dst) if File.exist?(src)

    # Fix 2: Remove weak_framework FirebaseFirestoreInternal (it's a static lib, not framework)
    installer.pods_project.targets.each do |target|
      if target.name == 'Pods-HouseholdBudget'
        target.build_configurations.each do |bc|
          if bc.build_settings['OTHER_LDFLAGS']
            bc.build_settings['OTHER_LDFLAGS'] = Array(bc.build_settings['OTHER_LDFLAGS']).reject { |f|
              f == '-weak_framework' || f == '"FirebaseFirestoreInternal"'
            }
          end
        end
      end
    end

    # Fix 3: Copy the pre-generated FirebaseAuth-Swift.h compatibility header
    # This header includes FIRAuthErrorCode (moved to Swift in Firebase Auth 11.x)
    # as well as FIRAuth, FIRMultiFactorResolver, FIRTOTPSecret, and other Swift-defined types
    # needed by RNFBAuth ObjC code.
    # The file ios/patches/FirebaseAuth-Swift.h is generated from the Firebase SDK
    # and stored in the repo for reproducible builds.
    patch_swift_h = File.join(File.dirname(__FILE__), "patches", "FirebaseAuth-Swift.h")
    if File.exist?(patch_swift_h)
      %w[Private Public].each do |scope|
        dir = File.join(installer.sandbox.root, "Headers", scope, "FirebaseAuth")
        swift_h = File.join(dir, "FirebaseAuth-Swift.h")
        if File.directory?(dir)
          FileUtils.cp(patch_swift_h, swift_h)
        end
      end
    end
  end
end
